# Generated by Django 6.0.2 on 2026-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_address_user_bio_user_is_google_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "House Owner"),
                    ("tenant", "Tenant"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
