# Generated by Django 6.0.2 on 2026-02-25 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_bathrooms_property_bathrooms_per_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='electricity_included',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='room',
            name='water_included',
        ),
        migrations.RemoveField(
            model_name='room',
            name='wifi_included',
        ),
        migrations.CreateModel(
            name='RoomFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=False)),
                ('water_included', models.BooleanField(default=False)),
                ('electricity_included', models.BooleanField(default=False)),
                ('gas_included', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('heater', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('microwave', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('security_guard', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('housekeeping', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('bed', models.BooleanField(default=False)),
                ('wardrobe', models.BooleanField(default=False)),
                ('study_table', models.BooleanField(default=False)),
                ('sofa', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='properties.room')),
            ],
        ),
    ]
