# Generated by Django 6.0.2 on 2026-02-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='submitted_by',
            field=models.CharField(choices=[('tenant', 'Tenant'), ('owner', 'Owner')], default='tenant', max_length=10),
        ),
    ]
