# Generated by Django 6.0.2 on 2026-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("complaints", "0002_complaint_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="complaint",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
