# Generated by Django 6.0.2 on 2026-02-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="cancelled_by",
            field=models.CharField(
                blank=True,
                choices=[("tenant", "Tenant"), ("owner", "Owner")],
                max_length=10,
                null=True,
            ),
        ),
    ]
