# Generated by Django 6.0.2 on 2026-02-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_booking_cancelled_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
