# Generated by Django 6.0.2 on 2026-02-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_booking_deleted_at_booking_is_deleted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="is_deleted",
            new_name="owner_deleted",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="deleted_at",
            new_name="owner_deleted_at",
        ),
        migrations.AddField(
            model_name="booking",
            name="tenant_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="tenant_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
